# Generated by Django 4.1.7 on 2023-02-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите email предприятия', max_length=254, unique=True)),
                ('country', models.CharField(help_text='Страна предприятия', max_length=100, verbose_name='Название страны')),
                ('city', models.CharField(help_text='Город предприятия', max_length=100, verbose_name='Название города')),
                ('street', models.CharField(help_text='Улица предприятия', max_length=100, verbose_name='Название улицы')),
                ('house_number', models.CharField(help_text='Номер дома предприятия', max_length=50, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название товара', max_length=50, verbose_name='Название товара')),
                ('model', models.CharField(help_text='Введите модель', max_length=50, verbose_name='Модель товара')),
                ('release_date', models.DateField(help_text='Укажите дату выхода на рынок товара', verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.SmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Укажите тип компании', verbose_name='Тип компании')),
                ('title', models.CharField(help_text='Укажите название предприятия', max_length=50, unique=True, verbose_name='Название компании')),
                ('debt', models.DecimalField(decimal_places=2, default=0, help_text='Укажите задолженность предприятия', max_digits=20, verbose_name='Задолженность')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('contacts', models.OneToOneField(help_text='Укажите контактные дынные предприятия', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='corp.contacts')),
                ('products', models.ManyToManyField(blank=True, help_text='Укажите продукты предприятия', related_name='companies', to='corp.product')),
                ('provider', models.ForeignKey(blank=True, help_text='Укажите поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='corp.company', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
    ]
